[tool.pysen]
version = "0.10"

[tool.pysen.lint]
enable_black = true
enable_flake8 = false
enable_isort = true
enable_mypy = true
mypy_preset = "entry"
line_length = 200
py_version = "py37"
[[tool.pysen.lint.mypy_targets]]
  paths = ["."]

